#include "Bullet.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Components/SphereComponent.h"
#include "Particles/ParticleSystem.h"
#include "EnemyCharacter.h"

ABullet::ABullet()
{
    PrimaryActorTick.bCanEverTick = true;

    // ğŸ”¹ ì¶©ëŒ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
    collisionComp = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComp"));
    collisionComp->SetSphereRadius(13);
    collisionComp->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    collisionComp->SetCollisionObjectType(ECC_GameTraceChannel1);
    collisionComp->SetCollisionResponseToAllChannels(ECR_Ignore);
    collisionComp->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);  
    collisionComp->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);
    collisionComp->OnComponentHit.AddDynamic(this, &ABullet::OnHit);
    RootComponent = collisionComp;

    // ğŸ”¹ ì´ì•Œì˜ ë©”ì‰¬
    bodyMeshComp = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("BodyMeshComp"));
    bodyMeshComp->SetupAttachment(collisionComp);
    bodyMeshComp->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    bodyMeshComp->SetRelativeScale3D(FVector(0.12f));

    // ğŸ”¹ ì´ì•Œì˜ ì›€ì§ì„ (ë°œì‚¬ ì†ë„, ì¤‘ë ¥ ì˜í–¥)
    movementComp = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("MovementComp"));
    movementComp->SetUpdatedComponent(collisionComp);
    movementComp->InitialSpeed = 5000;
    movementComp->MaxSpeed = 5000;
    movementComp->bShouldBounce = false; 
    movementComp->ProjectileGravityScale = 0.0f;  


    InitialLifeSpan = 3.0f;


    ImpactEffect = LoadObject<UParticleSystem>(nullptr, TEXT("/Game/Items/Effects/ParticleSystems/Weapons/AssaultRifle/Impacts/P_AssaultRifle_IH.P_AssaultRifle_IH"));

    if (!ImpactEffect)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ ImpactEffect ë¡œë“œ ì‹¤íŒ¨! ê²½ë¡œë¥¼ í™•ì¸í•˜ì„¸ìš”."));
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("âœ… ImpactEffect ë¡œë“œ ì„±ê³µ!"));
    }
}


void ABullet::BeginPlay()
{
    Super::BeginPlay();
}

void ABullet::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
}

void ABullet::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit)
{
    if (OtherActor && OtherActor != this && OtherActor != GetOwner())
    {
        // ğŸ”¹ ì  ìºë¦­í„°ì¸ì§€ í™•ì¸
        if (OtherActor->ActorHasTag("Enemy") || OtherActor->IsA(AEnemyCharacter::StaticClass()))
        {
            UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ ì´ì•Œì´ ì ì„ ë§ì¶¤! (%s)"), *OtherActor->GetName());

            UGameplayStatics::ApplyDamage(OtherActor, DamageAmount, GetInstigatorController(), this, UDamageType::StaticClass());

            if (ImpactEffect)
            {
                UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), ImpactEffect, Hit.ImpactPoint, FRotator::ZeroRotator);
            }

            Destroy();
        }
        else
        {
            UE_LOG(LogTemp, Warning, TEXT("ğŸ§± ì´ì•Œì´ í™˜ê²½ ì˜¤ë¸Œì íŠ¸ì— ë§ìŒ! (%s)"), *OtherActor->GetName());
        }
    }
}



