#include "Gun.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "Bullet.h"
#include "PlayerCharacter.h"
#include "GameFramework/ProjectileMovementComponent.h"

AGun::AGun()
{
    PrimaryActorTick.bCanEverTick = true;

    GunStaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("GunStaticMesh"));
    SetRootComponent(GunStaticMesh);

    MuzzleLocation = CreateDefaultSubobject<USceneComponent>(TEXT("MuzzleLocation"));
    MuzzleLocation->SetupAttachment(GunStaticMesh);

    CurrentAmmo = MaxAmmo;
}

int32 AGun::GetCurrentAmmo() const
{
    return CurrentAmmo;
}

int32 AGun::GetMaxAmmo() const
{
    return MaxAmmo;
}

void AGun::Fire()
{
    if (CurrentAmmo > 0)
    {
        CurrentAmmo--;

        if (!BulletFactory)
        {
            UE_LOG(LogTemp, Error, TEXT("Bullet Factoryê°€ ì„¤ì •ë˜ì§€ ì•ŠìŒ! BP_Bulletì„ ìë™ í• ë‹¹í•©ë‹ˆë‹¤."));
            AutoAssignBulletFactory(); // Bullet Factory ìë™ í• ë‹¹
        }

        if (BulletFactory)
        {
            UWorld* World = GetWorld();
            if (World)
            {
                FVector MuzzlePos = MuzzleLocation->GetComponentLocation();
                FRotator MuzzleRot = MuzzleLocation->GetComponentRotation();
                FVector ShotDirection = MuzzleRot.Vector();

                ABullet* SpawnedBullet = World->SpawnActor<ABullet>(BulletFactory, MuzzlePos, ShotDirection.Rotation());
                if (SpawnedBullet)
                {
                    UProjectileMovementComponent* BulletMovement = SpawnedBullet->FindComponentByClass<UProjectileMovementComponent>();
                    if (BulletMovement)
                    {
                        BulletMovement->Velocity = ShotDirection * BulletMovement->InitialSpeed;
                    }

                    UE_LOG(LogTemp, Warning, TEXT("ì´ì•Œ ìŠ¤í° ì„±ê³µ!"));
                }
            }
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("Bullet Factory ìë™ í• ë‹¹ ì‹¤íŒ¨! ë¸”ë£¨í”„ë¦°íŠ¸ ì„¤ì •ì„ í™•ì¸í•˜ì„¸ìš”."));
        }
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("íƒ„ì•½ ì—†ìŒ!"));
    }
}

void AGun::Reload()
{
    UE_LOG(LogTemp, Warning, TEXT("ì¬ì¥ì „!"));
    CurrentAmmo = MaxAmmo;
}

void AGun::BeginPlay()
{
    Super::BeginPlay();

    APlayerCharacter* PlayerCharacter = Cast<APlayerCharacter>(UGameplayStatics::GetPlayerCharacter(GetWorld(), 0));
    if (!PlayerCharacter)
    {
        UE_LOG(LogTemp, Error, TEXT("Gun: í”Œë ˆì´ì–´ ìºë¦­í„°ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤!"));
        return;
    }

    FName WeaponSocket = "GunSocket_R";
    AttachToComponent(PlayerCharacter->GetMesh(), FAttachmentTransformRules::SnapToTargetIncludingScale, WeaponSocket);

    // ìë™ìœ¼ë¡œ Bullet Factory ì„¤ì •
    AutoAssignBulletFactory();

    UE_LOG(LogTemp, Warning, TEXT("%sê°€ í”Œë ˆì´ì–´ ì†ì— ì¥ì°©ë¨!"), *GetName());
}

void AGun::SetGunMeshAndBullet(UStaticMesh* NewMesh, TSubclassOf<ABullet> NewBulletFactory)
{
    if (NewMesh)
    {
        GunStaticMesh->SetStaticMesh(NewMesh);
        UE_LOG(LogTemp, Warning, TEXT("ì´ ë©”ì‰¬ ë³€ê²½ ì™„ë£Œ: %s"), *NewMesh->GetName());
    }

    if (NewBulletFactory)
    {
        BulletFactory = NewBulletFactory;
        UE_LOG(LogTemp, Warning, TEXT("ì´ì•Œ ê³µì¥ ì„¤ì • ì™„ë£Œ"));
    }
}

/** ğŸ”¥ BP_Bulletì„ ìë™ìœ¼ë¡œ ì„¤ì •í•˜ëŠ” í•¨ìˆ˜ */
void AGun::AutoAssignBulletFactory()
{
    if (BulletFactory)
    {
        return; // ì´ë¯¸ ì„¤ì •ë˜ì–´ ìˆë‹¤ë©´ ë³€ê²½í•˜ì§€ ì•ŠìŒ
    }

    UWorld* World = GetWorld();
    if (!World)
    {
        UE_LOG(LogTemp, Error, TEXT("Bullet Factory ìë™ í• ë‹¹ ì‹¤íŒ¨: Worldê°€ ì—†ìŠµë‹ˆë‹¤!"));
        return;
    }

    // ê¸°ë³¸ Bullet Blueprint ê²½ë¡œ
    FString BulletPath = TEXT("/Game/Items/Blueprints/BP_Bullet.BP_Bullet_C");

    // ë¸”ë£¨í”„ë¦°íŠ¸ì—ì„œ íƒ„í™˜ í´ë˜ìŠ¤ ë¡œë“œ
    UClass* BulletClass = LoadClass<ABullet>(nullptr, *BulletPath);
    if (BulletClass)
    {
        BulletFactory = BulletClass;
        UE_LOG(LogTemp, Warning, TEXT("Bullet Factory ìë™ ì„¤ì • ì™„ë£Œ! BP_Bulletì´ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤."));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("Bullet Factory ìë™ ì„¤ì • ì‹¤íŒ¨! ë¸”ë£¨í”„ë¦°íŠ¸ ê²½ë¡œë¥¼ í™•ì¸í•˜ì„¸ìš”."));
    }
}
