#include "Pistol.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "Bullet.h"
#include "DrawDebugHelpers.h"
#include "PlayerCharacter.h"
#include "Camera/CameraComponent.h"

APistol::APistol()
{


    static ConstructorHelpers::FClassFinder<AActor> BulletBP(TEXT("/Game/Items/Blueprints/BP_Bullet.BP_Bullet_C"));

    if (BulletBP.Succeeded())
    {
        BulletFactory = BulletBP.Class;
        UE_LOG(LogTemp, Warning, TEXT("Pistol ìƒì„±ì: Bullet Factory ìë™ ì„¤ì • ì™„ë£Œ!"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("Pistol ìƒì„±ì: Bullet Factory ìë™ ì„¤ì • ì‹¤íŒ¨! ë¸”ë£¨í”„ë¦°íŠ¸ ê²½ë¡œ í™•ì¸ í•„ìš”."));
    }

    // ğŸ”¥ GunStaticMeshê°€ nullptrì´ë©´ ë¡œê·¸ ì¶œë ¥ í›„ ì¤‘ë‹¨
    if (!GunStaticMesh)
    {
        UE_LOG(LogTemp, Error, TEXT("GunStaticMeshê°€ nullptrì…ë‹ˆë‹¤! MuzzleLocationì„ ì—°ê²°í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
    }
    if (!MuzzleLocation)
    {
        // ğŸ”¥ ì¤‘ë³µ ìƒì„± ë°©ì§€
        MuzzleLocation = CreateDefaultSubobject<USceneComponent>(TEXT("MuzzleLocation"));
        MuzzleLocation->SetupAttachment(GunStaticMesh);
        MuzzleLocation->SetRelativeLocation(FVector(0.f, 30.f, 10.f));
        UE_LOG(LogTemp, Warning, TEXT("MuzzleLocation ìƒì„± ì™„ë£Œ!"));
    }


    MaxAmmo = 12;
    CurrentAmmo = MaxAmmo;
}

void APistol::BeginPlay()
{
    Super::BeginPlay();
    AutoAssignBulletFactory();
    /*APlayerCharacter* PlayerCharacter = Cast<APlayerCharacter>(UGameplayStatics::GetPlayerCharacter(GetWorld(), 0));
    if (!PlayerCharacter)
    {
        UE_LOG(LogTemp, Error, TEXT("Pistol: í”Œë ˆì´ì–´ ìºë¦­í„°ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤!"));
        return;
    }*/

    // ğŸ”¹ ì´ì„ ìºë¦­í„° ì†ì— ë¶€ì°©
    /*FName WeaponSocket = "GunSocket_R";
    AttachToComponent(PlayerCharacter->GetMesh(), FAttachmentTransformRules::SnapToTargetNotIncludingScale, WeaponSocket);*/

    // ğŸ”¹ ì´ íšŒì „ê°’ì„ ë³´ì • (Yaw 180ë„ íšŒì „)
    FRotator NewRotation = GetActorRotation();
    NewRotation.Yaw += 180.0f;
    SetActorRotation(NewRotation);

    UE_LOG(LogTemp, Warning, TEXT("%sê°€ í”Œë ˆì´ì–´ ì†ì— ì˜¬ë°”ë¥´ê²Œ ì¥ì°©ë¨!"), *GetName());
}



void APistol::Fire()
{
    if (!BulletFactory)
    {
        UE_LOG(LogTemp, Error, TEXT("Pistol: Bullet Factoryê°€ ì„¤ì •ë˜ì§€ ì•ŠìŒ! ìë™ í• ë‹¹ ì‹œë„."));
        AutoAssignBulletFactory();
    }


    UWorld* World = GetOuter()->GetWorld();
    if (!World)
    {
        UE_LOG(LogTemp, Error, TEXT("Worldd ì—†ìŒ!"));
        return;
    }
    if (!MuzzleLocation)
    {
        UE_LOG(LogTemp, Error, TEXT(" MuzzleLocation"));
        return;
    }

    FVector MuzzlePos = MuzzleLocation->GetComponentLocation();
    FRotator MuzzleRot = MuzzleLocation->GetComponentRotation();
    FVector ShotDirection = MuzzleRot.Vector();

    FVector TraceStart = MuzzlePos;
    FVector TraceEnd = TraceStart + (ShotDirection * Range);

    FHitResult HitResult;
    FCollisionQueryParams QueryParams;
    QueryParams.AddIgnoredActor(this);

    bool bHit = World->LineTraceSingleByChannel(
        HitResult, TraceStart, TraceEnd, ECC_Pawn, QueryParams);

    DrawDebugLine(World, TraceStart, TraceEnd, FColor::Green, false, 5.0f, 0, 5.0f);

    if (bHit)
    {
        AActor* HitActor = HitResult.GetActor();
        if (HitActor)
        {
            UE_LOG(LogTemp, Warning, TEXT("íŠ¸ë ˆì´ìŠ¤ ëª…ì¤‘! ë§ì€ ëŒ€ìƒ: %s"), *HitActor->GetName());

            
            float AppliedDamage = UGameplayStatics::ApplyDamage(
                HitActor,
                Damage,
                GetOwner()->GetInstigatorController(),
                this,
                nullptr
            );

            UE_LOG(LogTemp, Warning, TEXT("ê¶Œì´ì´ %sì— ëª…ì¤‘! í”¼í•´ëŸ‰: %f"), *HitActor->GetName(), AppliedDamage);
        }
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("íŠ¸ë ˆì´ìŠ¤ ë¯¸ì ì¤‘!"));
    }

    
    ABullet* SpawnedBullet = World->SpawnActor<ABullet>(BulletFactory, MuzzlePos, ShotDirection.Rotation());
    if (SpawnedBullet)
    {
        UE_LOG(LogTemp, Warning, TEXT("ì´ì•Œ ìŠ¤í° ì„±ê³µ!"));
    }
    Super::Fire();
}



void APistol::Reload()
{
    UE_LOG(LogTemp, Warning, TEXT("ê¶Œì´ì€ ë¬´í•œ íƒ„ì°½ì´ë¯€ë¡œ ì¬ì¥ì „ì´ í•„ìš” ì—†ìŒ!"));
}


void APistol::AutoAssignBulletFactory()
{
    if (BulletFactory) return;

    FString BulletPath = TEXT("/Game/Items/Blueprints/BP_Bullet.BP_Bullet");
    UClass* BulletClass = LoadClass<ABullet>(nullptr, *BulletPath);

    if (BulletClass)
    {
        BulletFactory = BulletClass;
        UE_LOG(LogTemp, Warning, TEXT("Pistol: Bullet Factory ìë™ ì„¤ì • ì™„ë£Œ!"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("Pistol: Bullet Factory ìë™ ì„¤ì • ì‹¤íŒ¨! ë¸”ë£¨í”„ë¦°íŠ¸ ê²½ë¡œ í™•ì¸ í•„ìš”."));
    }
}
